"use client"
import './globals.css'
import { Urbanist } from 'next/font/google'
import { RecoilRoot, useRecoilValue } from 'recoil'
import middleware from '@/middleware'
import jwt_decode from "jwt-decode";
import { useEffect } from 'react'
import Cookies from 'js-cookie'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';


const inter = Urbanist({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
})

const metadata = {
  title: 'CRUD mangment system',
  description: 'Generated by create next app',
}


// export const BaseUrl = "https://inventory-apis.up.railway.app"
export default function RootLayout({ children }) {
  // const tokken = Cookies.get("accessToken")
  // var decoded = jwt_decode(tokken);
  // var currentDate = new Date()
  // useEffect(() => {
  //   if ((decoded.exp * 1000) < currentDate.getTime()) {
  //     Cookies.set("islogged", false)
  //   }
  // }, [children])
  return (
    <html lang="en">

      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>

      <RecoilRoot>
        <body className={inter.className}>
          {/* <ToastContainer style={{ width: "500px" }} theme="colored" rtl={true} draggable={true} draggablePercent={50} /> */}
          {children}
          {middleware}
        </body>
      </RecoilRoot>
    </html>
  )
}
